import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/index.scss";
import "@/styles/toolStyles.css";

import Navbar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={inter.className}>
        <Navbar maxWidth={"max-w-[1320px]"} navType={""} />
        <div className={"min-h-screen overflow-x-hidden pt-[84px]"} >
          <main className="mx-auto ">
            {children}
          </main>
        </div>
        <Footer />

      </body>
    </html>
  );
}
